Fleshing Out Status Effects
TheOldRealms/TOW_Core_Old pull request #14
Opened 2021-05-17 03:39 UTC by tristanka

Added the XML for Status Effects as well as the manager to read them in and store them in memory. Various QOL changes. Commits are a little descriptive but I won't be surprised to see questions in the comments 😄 

The diff is a little ugly but I had to rename the StatusEffect namespace to StatusEffects to avoid the collision between the StatusEffect class and the namespace. Sorry.

Some TODOs: 

AttributeManager and StatusEffectManager basically follow the same pattern, so maybe have some kind of XML manager that handles generics?

Attributes maybe should be XML serializable like StatusEffect.

Need to create DamageManager (name needs work) that gets all of the stats that affect damage and can recalculate the damage of a Blow. Right now, damage is being handled directly in AgentExtensions.ApplyDamage() and StatusEffectComponent. Ideally, StatusEffectComponent will provide its EffectAggregate (rename this to DamageModifierData or something?) to the centralized class when calculating damage on the owner of the StatusEffectComponent (the agent). This is basically word salad but hopefully it gets the point across - I'll draw something if necessary

2021-05-17 09:46 UTC, Z3rca commented on Battle/StatusEffects/StatusEffectMissionLogic.cs
> +        public override void OnMissionTick(float dt)
I did this the same way before. For some reasons it created a complete overload. Did you check the performance even with a very high unit count?

2021-05-17 09:48 UTC, Z3rca commented on Battle/StatusEffects/StatusEffectComponent.cs
> +            {
clever. makes things more readable.

2021-05-17 09:57 UTC, Z3rca commented on Battle/StatusEffects/StatusEffectComponent.cs
> +        {
effect aggregate makes things more readable and reduces acesses I guess... Great work

2021-05-17 10:06 UTC, Z3rca commented on Battle/StatusEffects/StatusEffectComponent.cs
> +            foreach (StatusEffect effect in _currentEffects.ToList())
I do not know if this can be costly. rearanging those effects as list for each frame might not be a very good idea.

2021-05-17 10:06 UTC, Z3rca commented on Battle/StatusEffects/StatusEffectComponent.cs
> +        private HashSet<StatusEffect> _currentEffects;
I like your approach of not using a second list or the dictionary for the status effect. However I have some thoughts on this down below

2021-05-17 10:07 UTC, Z3rca commented on Battle/StatusEffects/StatusEffectComponent.cs
> +            foreach (StatusEffect effect in _currentEffects.ToList())
still if this survives a 400 unit stress test with 9 effects I am fine :P

2021-05-17 10:15 UTC, Z3rca commented on Battle/Extensions/AgentExtensions.cs
> +            agent.GetComponent<StatusEffectComponent>().RunStatusEffect(effectId);
We should maybe create and exception here aswell... it could be the very rare case that the effect we are asking is not available. or something is hit and the status effect is applied on something that is not posessing this in his status effect pool. We somehow have to handle this problem I guess, or create an informative exception.

2021-05-17 10:18 UTC, Z3rca commented on Battle/StatusEffect/StatusEffect.cs
> -﻿using System.Collections.Generic;
just a personal view, I wouldn't delete everything, or atleast only nuke inside the file. For a moment I just thought we went complete rage

2021-05-17 10:30 UTC, Z3rca commented
generally it follows what we have spoken off and might even reduce the load since not that many timers are needed. I still don't get why my solution with a similar logic didn't worked for me. that might be because I used a dictionary instead of an hashmap. Also I didn't get that my foreach loop didn't worked, which made my script whole more uglier than it once intended it was. There might be some performance issues of using the hash map. still, if this solution can be tested with 400 active agents and maybe 8-9 effects(and they show some values), I am totally happy with that solution. The solution is easy to read, and removed some redundancies, I was not able to remove for some reasons.


Maybe make ontop of this changes a little stress test, tell us the results and then we can merge this one here.

2021-05-17 10:34 UTC, Z3rca reviewed
look in the conversations tab, make a stress test, tell us the results(CPU, RAM)  vs vanilla. Apart from this good work

2021-05-17 17:50 UTC, Finu commented on Battle/Extensions/AgentExtensions.cs
> +                    if (agent != null && (agentIsActive || agentIsRouted))
This agent !=null could be first line check - as it is used in both if branches and - if not null all this calculation is not necessary. Also this (agentIsActive || agentIsRouted) could be done first  int this else clause if not - no need to create Blow

2021-05-17 17:53 UTC, Finu commented on Battle/Extensions/AgentExtensions.cs
> +                TOWCommon.Log("ApplyDamage: attempted to damage agent, but: " + e.Message, LogLevel.Error);
Just  thought - maybe not to this review but general 
Create TOWCommon.proper TOWCommon.Error TOWCommon.Warn - less typping in long run

2021-05-17 17:58 UTC, Finu commented on Battle/AttributeSystem/CustomAgentComponents/UndeadMoraleAgentComponent.cs
> +            Agent.ApplyStatusEffect("crumble");
Maybe adding Enum for those values would be handy

2021-05-17 23:28 UTC, tristanka commented on Battle/StatusEffects/StatusEffectComponent.cs
> +            foreach (StatusEffect effect in _currentEffects.ToList())
Sent video of a 10 effect 200 unit stress test in discord, getting 60-90 fps, so it seems fine. I'm calling ToList() here because I was getting a ConcurrentModificationException (or something along those lines, dont remember the exact exception) when accessing the currentEffects directly. ToList() gives us a new enumerable to iterate over, so we won't get burned if the _currentEffects set gets modified during enumeration

2021-05-17 23:29 UTC, tristanka commented on Battle/StatusEffect/StatusEffect.cs
> -﻿using System.Collections.Generic;
I didn't actually delete anything, I just renamed the namespace. The way git handles this is to show complete file deletion and recreation under a new namespace. I can make sure to separate that into another commit in the future so diffs more readable though.

2021-05-17 23:39 UTC, tristanka commented on Battle/Extensions/AgentExtensions.cs
> +                    if (agent != null && (agentIsActive || agentIsRouted))
Updated this block if you want to take a look at the new implementation 🙂 I think I cleaned up the logic a bit. Thanks for pointing it out

2021-05-17 23:40 UTC, tristanka commented on Battle/AttributeSystem/CustomAgentComponents/UndeadMoraleAgentComponent.cs
> +            Agent.ApplyStatusEffect("crumble");
I'd like to do this, noted. Might not make it in this branch though

2021-05-18 12:55 UTC, Z3rca approved these changes
I am fine with it. The sugested changes are still in line with communicated design and make it work better because of the reduced number of timers. since the test ran good, I am happy with the changes.

2021-05-18 16:12 UTC, hunharibo requested changes

2021-05-18 16:12 UTC, hunharibo commented on Battle/Extensions/AgentExtensions.cs
> +                    agent.Health -= damageAmount;
i still don't like direct health manipulation. A bunch of logic doesn't run when you don't register damage via RegisterBlow. can we maybe find an alternative solution to this?

2021-05-18 16:12 UTC, hunharibo commented on Battle/StatusEffects/StatusEffectManager.cs
> +            XmlSerializer serializer = new XmlSerializer(typeof(StatusEffectList));
why do you even need a custom List class for StatusEffects? The class literally only containst a public List<StatusEffect> property. You can do:
`XmlSerializer serializer = new XmlSerializer(typeof(List<StatusEffect>))`
directly

2021-05-19 01:06 UTC, tristanka commented on Battle/Extensions/AgentExtensions.cs
> +                    agent.Health -= damageAmount;
Conversation resolved internally, stays for now, but should be replaced eventually with a system to allow callbacks from various damage types being applied (damage calculation system?)

2021-05-19 01:13 UTC, tristanka commented on Battle/StatusEffects/StatusEffectManager.cs
> +            XmlSerializer serializer = new XmlSerializer(typeof(StatusEffectList));
Resolved by specifying root attribute in the serializer constructor

 `XmlSerializer serializer = new XmlSerializer(typeof(List<StatusEffect>), new XmlRootAttribute("StatusEffects"));`

2021-05-19 10:20 UTC, Z3rca reviewed
Mostly comments, why the xml is not part of my solution doesn't make sense to me, or I got something wrong in the folder/solution structure

2021-05-19 10:20 UTC, Z3rca commented on Battle/TOWBattleUtilities.cs
> +        public static void ApplyStatusEffectToAgentsInArea(Vec2 center, float radius, string effectId, Agent damager = null, bool enemyOnly = false)
for later, maybe add a prog chance, so we have new level of control of such status effects. so efor each agent in your list, you apply the status effect just by chance

2021-05-19 10:20 UTC, Z3rca commented on Utilities/TOWParticleSystem.cs
> +        public static List<ParticleSystem> ApplyParticleToAgent(Agent agent, string particleId, out List<GameEntity> childEntities, ParticleIntensity intensity = ParticleIntensity.High)
also something for later, we should maybe add a new particle effect Component on each participant. This controls already instantiated particle effects on the agent. the entities can be turned on off over such controller instead of instantiating them at runtime. that might actually enhance the performance and avoid in critical situations like when many entities are affected at once, the instantiatiion of such. But as already state, we should only consider it , when we run into massiv perofrmance issues.

2021-05-19 10:20 UTC, Z3rca commented on ModuleData/tow_statuseffects.xml
> +<?xml version="1.0" encoding="utf-8" ?>
the status effect XML is not part of my solution? Maybe I did something wrong. it is only found in a attached folder.

2021-05-19 17:16 UTC, hunharibo approved these changes
i think we should merge, fix issues later if they arise. I cant see any more problems with this just by looking at it.

2021-05-19 20:29 UTC, merged