Introduce new font
TheOldRealms/TOW_Core_Old pull request #15
Opened 2021-05-17 18:59 UTC by Finu

Font texture 1024/1024 later on it can be replaced with .fnt file and asset ui_font_9 with probably some better quality.

2021-05-17 19:18 UTC, hunharibo requested changes
As a general policy, we dont include copypaste information from the base game in any of our XMLs unless they are needed explicitly. Please refactor the NativeSpriteData.XML so it uses our already existing towSpriteData.xml and only include additions, not the entire native xml with all entries.

2021-05-17 22:21 UTC, Finu commented
Learned something new - thought it won't work like this - but it seems it worked - thnks

2021-05-18 16:15 UTC, hunharibo approved these changes
Looks good. Approved.

2021-05-19 00:32 UTC, tristanka approved these changes

2021-05-22 21:42 UTC, merged